Algoritmo "Area"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Apresentar a área do retangulo
// Autor(a)    : João Victor
// Data atual  : 31/08/2026
Var
base, altura, area: real

Inicio
escreva ("Escreva a base: ")
leia (base)
escreva ("Escreva a altura: ")
leia (altura)
area<-base * altura
escreva ("A área é: ",area)

Fimalgoritmo