Algoritmo "antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Ler um número e apresentar seu antecessor
// Autor(a)    : João Victor
// Data atual  : 31/08/2026
Var
numero : inteiro
antecessor : inteiro


Inicio
escreva ("Escreva um número")
leia (numero)
antecessor<-numero - 1
escreva ("O numero antecessor é: ",antecessor)


Fimalgoritmo