Algoritmo "Exe01"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa
// Descrição   : Ler um valor e responder se é maior, menor ou igual a 10.
// Autor(a)    : João Victor
// Data atual  : 14/09/2026
Var
// Seção de Declarações das variáveis
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Escreva um valor: ")
leia(valor)

se valor > 10 entao
   escreval("É maior que 10!")
senao
se valor = 10 entao
   escreval("É 10!")
senao
   escreval("É menor que 10!")
fimse

Fimalgoritmo
