Algoritmo "Exe02"
// Disciplina  :Lógica de Programação
// Professor   : Jailson Costa
// Descrição   :  Ler um valor e escrever se é positivo ou negativo
//(considere o valor zero como positivo).
// Autor(a)    : João Victor
// Data atual  : 14/09/2026
Var
// Seção de Declarações das variáveis 
valor:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Escreva um valor: ")
leia(valor)
se valor < 0 entao
escreval ("É negativo")
senao
escreval("É positivo")
fimse



Fimalgoritmo