Algoritmo "ValorFinalComissao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Saiba o valor final do seu Salario após calculo de comissões
// Autor(a)    : João Victor
// Data atual  : 31/08/2026
Var
CarrosVendidos: real
ValorTotalVendas: real
SalarioFixo: real
ValorCarroVendido: real
SalarioFinal : real
Inicio
escreva ("Numero de carros vendidos: ")
leia (CarrosVendidos)
escreva ("Valor total de vendas: ")
leia (ValorTotalVendas)
escreva ("Digite seu salário Fixo: ")
leia (SalarioFixo)
escreva ("Valor por carro vendido: ")
leia (ValorCarroVendido)
ValorCarroVendido<- CarrosVendidos * ValorCarroVendido
ValorTotalVendas<- ValorTotalVendas * 5 / 100

SalarioFinal<- Salariofixo + ValorCarroVendido + ValorTotalVendas

escreva("Seu Salário Final é de: ",SalarioFinal)










Fimalgoritmo