Algoritmo "EXE13"

// Disciplina   : [Lógica de Programação]

// Professor   : Jailson COSTA

// Descrição   : Ler um valor e escrever se é positivo, negativo ou zero.

// Autor(a)    : João Victor

// Data atual  : 14/09/2026

Var

// Seção de Declarações das variáveis

valor:real



Inicio

// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("Digite um valor")

leia(valor)

se valor < 0 entao

escreval(valor, " é negativo")

senao

se valor > 0 entao

escreval(valor, " é positivo")

senao

escreval(valor, " é zero")



fimse

fimse



Fimalgoritmo

